name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout code
      uses: actions/checkout@v3

   
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.uswazafar }}
        password: ${{ secrets.uswa123@123 }}

   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.uswazafar }}
